// 自动生成：数据源自 projects/fengshui-analyst/references/fengshui-knowledge.md
// 请勿手工修改本文件——更新知识库 md 后重新运行 gen_kb.js 脚本再生成
const KB = {
  terms: [
    {cat:"外部环境类", saying:"门口正对路", term:"路冲", note:"道路直冲大门"},
    {cat:"外部环境类", saying:"路像箭一样射过来", term:"路冲/枪煞", note:"笔直道路直冲"},
    {cat:"外部环境类", saying:"对面楼角对着我", term:"尖角冲射/角煞", note:"建筑物尖角对准"},
    {cat:"外部环境类", saying:"两栋楼中间有条缝", term:"天斩煞", note:"两高楼间狭窄缝隙"},
    {cat:"外部环境类", saying:"对面玻璃墙反光", term:"光煞/反光煞", note:"玻璃幕墙反射"},
    {cat:"外部环境类", saying:"旁边有高压电塔", term:"火形煞/电磁煞", note:"高压电设施"},
    {cat:"外部环境类", saying:"窗外有烟囱对着", term:"冲射煞", note:"烟囱正对窗户"},
    {cat:"外部环境类", saying:"门前有电线杆", term:"顶心煞", note:"柱状物正对大门"},
    {cat:"外部环境类", saying:"后面有山/坡", term:"靠山/玄武有靠", note:"屋后有靠"},
    {cat:"外部环境类", saying:"前面很开阔", term:"明堂开阔", note:"屋前空间开阔"},
    {cat:"外部环境类", saying:"左边有高楼", term:"青龙方", note:"左侧环境"},
    {cat:"外部环境类", saying:"右边有高楼", term:"白虎方", note:"右侧环境"},
    {cat:"外部环境类", saying:"前面有楼挡着", term:"明堂受阻/案山过高", note:"前方遮挡"},
    {cat:"外部环境类", saying:"后面没依靠", term:"玄武无靠", note:"屋后空旷"},
    {cat:"外部环境类", saying:"左边低右边高", term:"龙低虎高", note:"左弱右强"},
    {cat:"外部环境类", saying:"附近有庙/教堂", term:"孤阳/孤阴煞", note:"宗教场所附近"},
    {cat:"外部环境类", saying:"附近有医院", term:"独阴煞", note:"阴气重"},
    {cat:"外部环境类", saying:"附近有墓地", term:"阴煞", note:"阴气极重"},
    {cat:"外部环境类", saying:"旁边在施工", term:"动土煞/声煞", note:"施工噪音影响"},
    {cat:"外部环境类", saying:"对面有牌坊/拱门", term:"形煞/压顶", note:"高大拱形物"},
    {cat:"水体环境类", saying:"水是弯的绕过来", term:"环抱水/玉带水", note:"水弯曲环抱为吉"},
    {cat:"水体环境类", saying:"水直直地流走", term:"直去水/牵牛水", note:"水直流为凶"},
    {cat:"水体环境类", saying:"水反弓对着我", term:"反弓水/弓背水", note:"水弯背对为凶"},
    {cat:"水体环境类", saying:"门前有个池塘", term:"明堂聚水", note:"屋前聚水"},
    {cat:"水体环境类", saying:"窗外能看到河", term:"见水", note:"可视范围内有水"},
    {cat:"水体环境类", saying:"水是脏的/臭的", term:"污水/秽水", note:"水质不佳"},
    {cat:"水体环境类", saying:"水声很大", term:"声煞/割脚水", note:"水声过大"},
    {cat:"水体环境类", saying:"水离房子很近", term:"割脚水", note:"水贴屋脚"},
    {cat:"水体环境类", saying:"有瀑布/急流", term:"急水/声煞", note:"水流湍急"},
    {cat:"水体环境类", saying:"门前有喷泉", term:"明堂动水", note:"人工水景"},
    {cat:"水体环境类", saying:"水从屋后流过", term:"背水", note:"屋后有水"},
    {cat:"水体环境类", saying:"两条河交汇处", term:"水口/三叉水口", note:"水流交汇"},
    {cat:"水体环境类", saying:"海边/湖边", term:"近水/大水", note:"大面积水体"},
    {cat:"水体环境类", saying:"排水沟对着门", term:"污水冲射", note:"排水方向"},
    {cat:"水体环境类", saying:"下雨积水", term:"积水/涝灾风险", note:"排水不良"},
    {cat:"室内布局类", saying:"大门对着后门", term:"穿堂煞", note:"前后门直通"},
    {cat:"室内布局类", saying:"大门对着窗户", term:"穿堂煞", note:"门对窗气直泄"},
    {cat:"室内布局类", saying:"床头上面有横梁", term:"横梁压顶", note:"梁压床头"},
    {cat:"室内布局类", saying:"沙发上面有横梁", term:"横梁压顶", note:"梁压座位"},
    {cat:"室内布局类", saying:"门对着门", term:"门冲", note:"两门相对"},
    {cat:"室内布局类", saying:"厕所门对着厨房门", term:"水火冲", note:"厕厨相对"},
    {cat:"室内布局类", saying:"厕所门对着卧室门", term:"秽气冲床", note:"厕对卧"},
    {cat:"室内布局类", saying:"厨房在房子中间", term:"中宫设灶/中宫受污", note:"中央为厨/厕"},
    {cat:"室内布局类", saying:"厕所房子中间", term:"中宫设厕", note:"中央为厕，极凶"},
    {cat:"室内布局类", saying:"镜子对着床", term:"镜煞/照床镜", note:"镜对床"},
    {cat:"室内布局类", saying:"镜子对着门", term:"镜照门", note:"镜对大门"},
    {cat:"室内布局类", saying:"楼梯对着大门", term:"牵牛煞", note:"楼梯冲门"},
    {cat:"室内布局类", saying:"进门就是楼梯", term:"牵牛煞", note:"入门见梯"},
    {cat:"室内布局类", saying:"床头对着门", term:"冲床", note:"床对房门"},
    {cat:"室内布局类", saying:"床在窗户下面", term:"窗下床", note:"床头靠窗"},
    {cat:"室内布局类", saying:"灶台对着水槽", term:"水火不相容", note:"灶水相对"},
    {cat:"室内布局类", saying:"灶台背对门", term:"背门灶", note:"灶背对门"},
    {cat:"室内布局类", saying:"进门能看到灶台", term:"开门见灶", note:"财库外露"},
    {cat:"室内布局类", saying:"走廊尽头是房间", term:"枪煞/箭煞", note:"长廊冲房"},
    {cat:"室内布局类", saying:"房间缺角", term:"缺角", note:"户型不规则"},
    {cat:"室内布局类", saying:"房子是三角形的", term:"火形屋/三角煞", note:"三角形户型"},
    {cat:"室内布局类", saying:"客厅在楼上", term:"上下颠倒", note:"格局颠倒"},
    {cat:"室内布局类", saying:"卧室在厨房上面", term:"火气上冲", note:"卧压灶"},
    {cat:"室内布局类", saying:"阳台对尖角", term:"尖角冲射", note:"阳台对尖角"},
    {cat:"室内布局类", saying:"大门对电梯口", term:"开口煞", note:"门对电梯"},
    {cat:"方位坐向类", saying:"门朝南", term:"子山午向/坐北朝南", note:"大门朝南"},
    {cat:"方位坐向类", saying:"门朝北", term:"午山子向/坐南朝北", note:"大门朝北"},
    {cat:"方位坐向类", saying:"门朝东", term:"酉山卯向/坐西朝东", note:"大门朝东"},
    {cat:"方位坐向类", saying:"门朝西", term:"卯山酉向/坐东朝西", note:"大门朝西"},
    {cat:"方位坐向类", saying:"门朝东南", term:"乾山巽向/坐西北朝东南", note:"大门朝东南"},
    {cat:"方位坐向类", saying:"门朝西北", term:"巽山乾向/坐东南朝西北", note:"大门朝西北"},
    {cat:"方位坐向类", saying:"门朝东北", term:"坤山艮向/坐西南朝东北", note:"大门朝东北"},
    {cat:"方位坐向类", saying:"门朝西南", term:"艮山坤向/坐东北朝西南", note:"大门朝西南"},
    {cat:"方位坐向类", saying:"阳台朝南", term:"向南/纳离气", note:"阳台方向"},
    {cat:"方位坐向类", saying:"窗户朝东", term:"纳震气", note:"窗户方向"},
    {cat:"方位坐向类", saying:"房子背靠山", term:"靠山/坐实", note:"屋后有靠"},
    {cat:"方位坐向类", saying:"房子面朝水", term:"朝空/面虚", note:"屋前有水"},
    {cat:"人物配命类", saying:"1985年生", term:"乙丑年命", note:"出生年份对应天干地支"},
    {cat:"人物配命类", saying:"1990年生", term:"庚午年命", note:"出生年份对应天干地支"},
    {cat:"人物配命类", saying:"属鼠", term:"子年生人", note:"生肖对应地支"},
    {cat:"人物配命类", saying:"属牛", term:"丑年生人", note:"生肖对应地支"},
    {cat:"人物配命类", saying:"属虎", term:"寅年生人", note:"生肖对应地支"},
    {cat:"人物配命类", saying:"属龙", term:"辰年生人", note:"生肖对应地支"},
    {cat:"人物配命类", saying:"属蛇", term:"巳年生人", note:"生肖对应地支"},
    {cat:"人物配命类", saying:"属马", term:"午年生人", note:"生肖对应地支"},
    {cat:"时间类", saying:"今年搬进来的", term:"入宅年份", note:"入住时间"},
    {cat:"时间类", saying:"去年装修的", term:"装修年份", note:"装修时间"},
    {cat:"时间类", saying:"房子是90年代建的", term:"建造年份", note:"建筑年代"},
    {cat:"时间类", saying:"住了快十年了", term:"居住时长", note:"居住年限"},
    {cat:"时间类", saying:"最近感觉不好", term:"流年不利", note:"近期运势变化"},
    {cat:"现代人造物类", saying:"对面玻璃幕墙反光", term:"光煞", note:"玻璃反射"},
    {cat:"现代人造物类", saying:"旁边有信号塔", term:"电磁煞/火形煞", note:"通信设施"},
    {cat:"现代人造物类", saying:"窗外有高架桥", term:"声煞/割脚水", note:"高架道路"},
    {cat:"现代人造物类", saying:"旁边有加油站", term:"火形煞/孤阳煞", note:"危险设施"},
    {cat:"现代人造物类", saying:"对面有烟囱", term:"冲射煞/独阳煞", note:"工业烟囱"},
    {cat:"现代人造物类", saying:"旁边有变电站", term:"火形煞/电磁煞", note:"电力设施"},
    {cat:"现代人造物类", saying:"窗外有广告牌", term:"形煞/压顶", note:"大型广告"},
    {cat:"现代人造物类", saying:"对面有尖顶建筑", term:"火形煞/尖角冲射", note:"尖顶建筑"},
    {cat:"现代人造物类", saying:"旁边有工厂", term:"声煞/味煞", note:"工业设施"},
    {cat:"现代人造物类", saying:"窗外有路灯杆", term:"顶心煞", note:"杆状物"},
    {cat:"现代人造物类", saying:"门口有垃圾桶", term:"秽气", note:"垃圾设施"},
    {cat:"现代人造物类", saying:"旁边有停车场", term:"声煞/动土", note:"车辆进出"},
    {cat:"现代人造物类", saying:"对面有圆形建筑", term:"金形煞", note:"圆形建筑"},
    {cat:"现代人造物类", saying:"旁边有水塔", term:"形煞", note:"高大水塔"},
    {cat:"现代人造物类", saying:"窗外有天线", term:"火形煞", note:"天线设施"},
    {cat:"现代人造物类", saying:"门口有石墩/隔离桩", term:"顶心煞", note:"柱状障碍物"},
    {cat:"现代人造物类", saying:"对面有拱形门", term:"形煞", note:"拱形结构"},
    {cat:"现代人造物类", saying:"旁边有铁路", term:"声煞/割脚煞", note:"铁路设施"},
    {cat:"现代人造物类", saying:"窗外有大树", term:"树撞煞/顶心煞", note:"大树过近"},
    {cat:"现代人造物类", saying:"对面有围墙尖角", term:"尖角冲射", note:"围墙尖角"},
  ],
  termTotal: 105,
  buildingTypes: [
    {code:"T1", name:"传统低层住宅", keywords:"3层以下/实墙/院子", focus:"完整四兽分析，院落布局"},
    {code:"T2", name:"多层/小高层", keywords:"4-12层/单元式", focus:"楼层选择，单元门向"},
    {code:"T3", name:"高层/超高层", keywords:"13层以上/玻璃幕墙/核心筒", focus:"高空风振修正，玻璃幕墙光煞"},
    {code:"T4", name:"别墅/独栋", keywords:"独立建筑/花园", focus:"完整四兽，花园水法"},
    {code:"T5", name:"商业/办公写字楼", keywords:"开放式/公共走廊", focus:"动线规划，分区布局"},
    {code:"T6", name:"工业厂房/仓库", keywords:"大跨度/机器设备", focus:"动线/通风/安全分区"},
    {code:"T7", name:"公共建筑", keywords:"医院/学校/图书馆", focus:"功能优先，安全规范"},
    {code:"T8", name:"开放式/无墙建筑", keywords:"凉亭/帐篷/移动房屋", focus:"藏风困难，以实用为主"},
    {code:"T9", name:"地下/半地下", keywords:"地下室/防空洞", focus:"采光通风极差，潮湿问题"},
    {code:"T10", name:"历史/文物建筑", keywords:"有保护等级", focus:"尊重原貌，有限调整"},
  ],
  classics: [
    {book:"葬书", theme:"风水理论根基，\"藏风聚气\"核心思想", quotes:[
      {text:"气乘风则散，界水则止", explain:"气流遇到风会散开，遇到水会停聚", scene:"判断藏风聚气格局"},
      {text:"玄武垂头", explain:"后方靠山要低俯有情，如点头状", scene:"评估屋后靠山"},
      {text:"朱雀翔舞", explain:"前方明堂要开阔活跃，如鸟展翅", scene:"评估屋前明堂"},
      {text:"青龙蜿蜒", explain:"左侧护砂要曲折有情", scene:"评估左侧环境"},
      {text:"白虎顺俯", explain:"右侧护砂要温顺低伏", scene:"评估右侧环境"},
      {text:"葬者，乘生气也", explain:"选择有生气的地方", scene:"总体选址原则"},
      {text:"地势吉而有生气", explain:"地势要好且有生气", scene:"判断地气"},
      {text:"支葬其巅，垄葬其脚", explain:"山地葬高处，平地葬低处", scene:"地形判断"},
      {text:"左为青龙，右为白虎", explain:"左右护砂的称谓", scene:"方位判断"},
      {text:"前有污池，谓之朱雀", explain:"前方有水为朱雀", scene:"水法判断"},
      {text:"夫土者，气之体", explain:"土是气的载体", scene:"地质判断"},
      {text:"浅深得乘，风水自成", explain:"深浅要得当", scene:"布局调整"},
      {text:"经曰：地有四势，法有四从", explain:"地有四种态势", scene:"地形分类"},
      {text:"过水所以止来龙", explain:"水可以止住龙脉", scene:"水法应用"},
      {text:"外气横行，内气止生", explain:"外气横行为用，内气止聚为生", scene:"内外气判断"},
      {text:"占山观水，点穴观龙", explain:"看山要看水，点穴要看龙", scene:"分析方法"},
      {text:"水口不通，气聚其中", explain:"水口紧闭则气聚", scene:"水口判断"},
      {text:"山环水抱必有气", explain:"山环水抱的地方一定有气", scene:"总体判断"},
      {text:"龙真穴的，砂明水秀", explain:"龙脉真、穴位正、砂水明秀", scene:"综合评估"},
      {text:"明堂容万马，富贵传天下", explain:"明堂开阔则富贵", scene:"明堂评估"},
      {text:"龙怕孤单，穴怕寒", explain:"龙脉要有护从，穴位要有温暖感", scene:"环境评估"},
      {text:"山主人丁水主财", explain:"山影响人丁，水影响财运", scene:"山水作用"},
      {text:"得水为上，藏风次之", explain:"得水最重要，藏风其次", scene:"优先级判断"},
      {text:"气乘风则散", explain:"风大会散气", scene:"风口判断"},
      {text:"界水则止", explain:"水可以界气", scene:"水法原理"},
      {text:"形势顺而气从之", explain:"形势好气自然来", scene:"形势判断"},
      {text:"四势朝迎，气聚其中", explain:"四面朝拱则气聚", scene:"四势判断"},
      {text:"来积止聚，冲阳和阴", explain:"来龙积势，止水聚气", scene:"龙水配合"},
      {text:"土高水深，郁草茂林", explain:"土高水深之处草木茂盛", scene:"生气判断"},
      {text:"贵若千乘，富如万金", explain:"好风水主贵主富", scene:"效果描述"},
    ]},
    {book:"撼龙经", theme:"九星峦头，龙脉形态识别", quotes:[
      {text:"贪狼顿笏笋初生", explain:"贪狼星如山笋初生，尖秀挺拔", scene:"识别贪狼峰"},
      {text:"巨门天马三台行", explain:"巨门星如天马行空，方正平稳", scene:"识别巨门峰"},
      {text:"禄存孤曜独峥嵘", explain:"禄存星孤立高耸", scene:"识别禄存峰"},
      {text:"文曲梭花弄巧形", explain:"文曲星如梭花般曲折", scene:"识别文曲峰"},
      {text:"廉贞鼓焰冲天起", explain:"廉贞星如火焰冲天", scene:"识别廉贞峰"},
      {text:"武曲钟鼎盖群英", explain:"武曲星如钟鼎覆盖", scene:"识别武曲峰"},
      {text:"破军走戟锋芒露", explain:"破军星如戟锋芒外露", scene:"识别破军峰"},
      {text:"左辅凹凹如眠弓", explain:"左辅星如眠弓弯曲", scene:"识别左辅峰"},
      {text:"右弼隐踪无定形", explain:"右弼星隐踪不定", scene:"识别右弼峰"},
    ]},
    {book:"疑龙经", theme:"寻龙点穴，辨别龙脉真伪", quotes:[
      {text:"寻龙千里非迢递，一步一步须审细", explain:"寻龙要仔细审察", scene:""},
      {text:"龙楼宝殿去堂堂，此是龙家大吉方", explain:"龙楼宝殿为大吉之象", scene:""},
      {text:"真龙行度必起伏，假龙直去无变化", explain:"真龙有起伏，假龙直硬", scene:""},
    ]},
    {book:"青囊奥语", theme:"玄空风水核心理气", quotes:[
      {text:"雌与雄为交媾，阴阳配合为根本", explain:"阴阳配合为根本", scene:""},
      {text:"明倒杖，卦坐阴阳二宅上", explain:"立向要明阴阳", scene:""},
      {text:"天卦江东掌上寻，知了值千金", explain:"天卦掌诀的重要性", scene:""},
    ]},
    {book:"天玉经", theme:"理气核心，三元九运", quotes:[
      {text:"江东一卦从来吉，八神四个一", explain:"江东卦吉", scene:""},
      {text:"江南来龙江北向，江北来龙江南去", explain:"龙向配合", scene:""},
      {text:"父母排来到子息，须要认来脉", explain:"排龙诀要认来脉", scene:""},
    ]},
    {book:"雪心赋", theme:"形煞识别核心", quotes:[
      {text:"拔砂烹雪，须识其真", explain:"辨别形煞要识真伪", scene:"形煞判断原则"},
      {text:"水似弯弓，穴前朝聚", explain:"水弯如弓朝穴为吉", scene:"环抱水判断"},
      {text:"路如直射，穴后冲来", explain:"路直射冲穴为凶", scene:"路冲判断"},
      {text:"门对空阔，富贵之基", explain:"门对开阔为富贵", scene:"明堂判断"},
      {text:"屋背凹风，丁财两败", explain:"屋后有凹风则丁财受损", scene:"凹风煞判断"},
      {text:"两楼夹缝，天斩之凶", explain:"两楼间缝隙为天斩煞", scene:"天斩煞判断"},
      {text:"反弓之水，散财之象", explain:"反弓水主散财", scene:"反弓水判断"},
      {text:"直来直去，气不聚留", explain:"直路直水气不聚", scene:"直冲判断"},
    ]},
    {book:"水龙经", theme:"水法专论", quotes:[
      {text:"水绕山环，富贵之基", explain:"水绕山环为大吉", scene:""},
      {text:"水口紧锁，气聚其中", explain:"水口紧闭则气聚", scene:""},
      {text:"玉带环腰，富贵滔滔", explain:"水如玉带环腰大富", scene:""},
      {text:"反弓水射，财散人离", explain:"反弓水主散", scene:""},
      {text:"直来水急，冲射为凶", explain:"直冲水为凶", scene:""},
    ]},
    {book:"宅经", theme:"阳宅布局", quotes:[
      {text:"宅以形势为骨体，以泉水为血脉", explain:"宅的形势为骨架，水为血脉", scene:"总体布局"},
      {text:"以土地为皮肉，以草树为毛发", explain:"土地为皮肉，草木为毛发", scene:"环境评估"},
      {text:"以舍屋为衣服，以门户为冠带", explain:"房屋为衣，门户为冠", scene:"建筑评估"},
      {text:"门为宅口，灶为宅命", explain:"门是宅的嘴，灶是宅的命", scene:"门灶评估"},
      {text:"厅明室暗，阴阳得宜", explain:"厅要明亮，室要安静偏暗", scene:"采光评估"},
      {text:"前低后高，世出英豪", explain:"前低后高格局出人才", scene:"地势评估"},
      {text:"前高后低，长幼昏迷", explain:"前高后低格局不利", scene:"地势评估"},
      {text:"门旁有灶，主多口舌", explain:"门旁设灶多口舌", scene:"灶位评估"},
      {text:"厕对厨门，主病缠绵", explain:"厕所对厨房主病", scene:"厕厨关系"},
      {text:"床对门路，主不安宁", explain:"床对门路不安宁", scene:"床位评估"},
    ]},
    {book:"八宅明镜", theme:"八宅配命", quotes:[
      {text:"乾坎艮震为东四宅，巽离坤兑为西四宅", explain:"八卦分东西四组", scene:"宅卦分类"},
      {text:"东四命宜居东四宅，西四命宜居西四宅", explain:"命卦与宅卦要匹配", scene:"配命原则"},
      {text:"生气为天医，延年为伏位", explain:"四吉方名称", scene:"吉方判断"},
      {text:"绝命为五鬼，六煞为祸害", explain:"四凶方名称", scene:"凶方判断"},
    ]},
  ]
};